### ISSUE TITLE
Getting error on executing  Get-AzSKADOSecurityStatus command

### ISSUE THREAD

**Issue by jaideepjha** [azsk/ADOScanner#181]
## Getting error on executing  Get-AzSKADOSecurityStatus command</br>

I have installed and imported AzSK.ADO module. I am part of the Project Administrator group on the ADO project for which I want to get the security scan result. However when I run the command:
![image](https://user-images.githubusercontent.com/420531/119301534-44bced00-bc80-11eb-9435-32064ef2d9a8.png)

I am getting the error: _"Organization not found: Incorrect organization name or you do not have necessary permission to access the organization"_

Can someone please guide me what I am doing wrong here, and how I can get the expected outcome?
</br>

## Steps to reproduce

```PowerShell
Import-Module AzSK.ADO
Get-AzSKADOSecurityStatus -OrganizationName "OrgName" -ProjectNames "ProjectName"
```
## Expected behavior</br> 
Scan Result

## Actual behavior</br>
Getting error. Error Message: 
Organization not found: Incorrect organization name or you do not have necessary permission to access the organization.
InvalidOperation: Invalid JSON primitive: .

**Comment by arvindsingh-cloud** [comment]
This could be due to the logged in identity does not have access to the organization. 
To ensure that the ADOScanner use the correct identity, you can force the sign-in dialog to appear by setting a variable. 

Try the below commands in fresh PowerShell session, also ensure all other sessions are closed.
```PowerShell
$AzSKADOLoginUI = 1       ## Helps you ensure log in with the correct identity
Import-Module AzSK.ADO
Get-AzSKADOSecurityStatus -OrganizationName ‘$orgname’
```

**Comment by arvindsingh-cloud** [comment]
Fixed
