### ISSUE TITLE
Feature Request: Add repositories scans

### ISSUE THREAD

**Issue by SebastianSchuetze** [azsk/ADOScanner#25]
## Title</br>

Add repository scans to the module

## Description</br>

it would be nice if I could scan for the following things (not complete list)
* usage of branch policy best practices
* check for best practice repository settings

Is that a possibility to include it?

**Comment by abhaydaga** [comment]
Hi @SebastianSchuetze - we are working on adding security checks for repositories in the next 1-2 sprints.

**Comment by SebastianSchuetze** [comment]
very nice. Do you have some detail? Because one of our requirements is to analyse if repositories have branch policies activated to enforce pull requests.

We need to do that for hundreds of repositories.

**Comment by abhaydaga** [comment]
We are still working on the details. Will keep you posted. Branch policy is something we are looking into for potential security controls.

**Comment by abhaydaga** [comment]
As per our first pass, we will be adding few controls just at the project level to check repository settings (for example if CredScan is enabled to check for checked in secrets, email validation of user pushing changes, inheritance to repositories, branch policies etc.)

**Comment by SebastianSchuetze** [comment]
Thanks! Is there a place where I can subscribe for upcoming releases to get some how notified or a blog where new releases are published?

**Comment by brennaman** [comment]
Hey! Any updates on support for repository scans?  Is it still on the roadmap?

**Comment by abhaydaga** [comment]
@brennaman We have added 4 repository controls. They are evaluate at project scope i.e. all repos are cumulatively scanned in one control. For e.g., if you have 100 repos in a project, scan evaluations of all 100 repos will be reported via a single control result (mega control). Here are 4 checks that we have added:

1. **ADO_Project_SI_Review_Author_Email_Validation_Policy** - Enable commit author email validation to restrict commits to repositories from untrusted users.
2. **ADO_Project_DP_Inactive_Repos** - Inactive repositories must be removed if no more required.
3. **ADO_Project_AuthZ_Disable_Inherited_Permissions** - Do not allow inherited permission on repositories.
4. **ADO_Project_AuthZ_Repo_Grant_Min_RBAC_Access** - All teams/groups must be granted minimum required permissions on repositories.

**Comment by abhaydaga** [comment]
@SebastianSchuetze - version-wise updates will be released on our documentation repo soon. It will include updates from the first release to the latest one.

[ADO Security Scanner Documentation](https://github.com/azsk/ADOScanner-docs)

**Comment by abhaydaga** [comment]
@SebastianSchuetze we have added version-wise updates section to our documentation.

[Release Notes](https://github.com/azsk/ADOScanner-docs/tree/master/Release%20notes)

**Comment by brennaman** [comment]
@abhaydaga are you going to go further with repository scans?  possibly scans that flag no or weak branch policies.

**Comment by SebastianSchuetze** [comment]
could this maybe also include to attach container to it which can do secret scans on repos? would be cool to attach any container that can somehow run code checks for secrets or other policies within repositories.

I don't mean to replace products like white source or sonarqube.
