### ISSUE TITLE
ADO Security Scanner Extension's dashboard crashes browser and shows no results in the select dropdown

### ISSUE THREAD

**Issue by tsteenbakkers** [azsk/ADOScanner#621]
## About a week ago our existing ADO Security Scanner Dashboards have started to crash any browser tab (regardless of browser)

Besides this previously the select build dropdown used to show the various builds, now it is empty despite the fact that the logs have been uploaded to the extension storage (see proof below).

I think our extension storage for this extension might be highly populated as we've been using the scanner for a long while and run it fairly often. However Azure DevOps does not allow to look into this storage and does not clear it (assumingly) on a reinstall of the extension.</br>

## Steps to reproduce
- opening a dashboard with the ADO Security Scanner widget
## Expected behavior</br> 

- populated dropdown
- ability to read the details of a scan

## Actual behavior</br>

empty dropdown:

![image](https://user-images.githubusercontent.com/13012630/174061517-0de6dcf9-f4b2-4702-b2b2-fc10498f9e0e.png)

crashed browser tab:

![image](https://user-images.githubusercontent.com/13012630/174061628-dc9f29df-aa6e-4ea1-9945-35396a0044e9.png)

proof a log was uploaded:

![image](https://user-images.githubusercontent.com/13012630/174061831-fb2e8664-7546-4034-ba50-f89726a45081.png)

**Comment by v-dpardeshi** [comment]
Apologies for the inactivity on this thread. This issue has been addressed previously. Could you please reinstall the extension and retry running the ADO scanner extension scanner again?
