### ISSUE TITLE
Create extension for OnPrem server

### ISSUE THREAD

**Issue by huntantr** [azsk/ADOScanner#635]
## Title</br>
Create extension for OnPrem server

## Description</br>
Would like to utilize this tool with ADO Server 2022. A lot of the code seems to be hardcoded to use the web url. If this can become a parameter then it could be used with OnPrem as well.

**Comment by v-dpardeshi** [comment]
Currently, we do not support on-premises servers for extension. We are considering a parameterized approach for the web URL in the future, which would enable compatibility with on-premises servers.
